#cloud-config
# Cloud-init configuration for Oracle Linux instances

# Update system packages
package_update: true
package_upgrade: true

# Install required packages
packages:
  - python3
  - python3-pip
  - git
  - curl
  - wget
  - htop
  - vim
  - firewalld

# Create application user
users:
  - name: appuser
    groups: wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

# Configure firewall
runcmd:
  # Start and enable firewalld
  - systemctl start firewalld
  - systemctl enable firewalld
  
  # Allow SSH
  - firewall-cmd --permanent --add-service=ssh
  
  # Allow HTTP and HTTPS
  - firewall-cmd --permanent --add-service=http
  - firewall-cmd --permanent --add-service=https
  
  # Reload firewall
  - firewall-cmd --reload
  
  # Install pip packages
  - pip3 install --upgrade pip
  - pip3 install ansible
  
  # Configure SSH
  - sed -i 's/#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl restart sshd
  
  # Set timezone
  - timedatectl set-timezone America/New_York
  
  # Create application directory
  - mkdir -p /opt/application
  - chown appuser:appuser /opt/application

# Configure system settings
write_files:
  - path: /etc/motd
    content: |
      Welcome to Semaphore-managed Oracle Cloud Instance
      
      This instance was provisioned by Terraform and is managed by Semaphore UI.
      
      Instance Information:
      - OS: Oracle Linux 8
      - Managed by: Semaphore UI
      - Provisioned by: Terraform
      
      For support, contact your DevOps team.
    owner: root:root
    permissions: '0644'

  - path: /opt/application/info.txt
    content: |
      Instance provisioned at: $(date)
      Terraform managed: true
      Semaphore managed: true
    owner: appuser:appuser
    permissions: '0644'

# Final message
final_message: "Oracle Cloud instance setup complete! Instance is ready for Semaphore automation."
